import type { ReactNode } from 'react';
import {
  ArrowDown,
  ArrowSquareOut,
  ArrowUp,
  ArrowsDownUp,
  CalendarBlank,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDown,
  CaretLeft,
  CaretRight,
  Check,
  CheckCircle,
  Checks,
  Clock,
  Columns,
  Copy,
  DotsThree,
  EyeSlash,
  Funnel,
  Info,
  List,
  MagnifyingGlass,
  Microphone,
  Stop,
  UploadSimple,
  Warning,
  Wrench,
  X,
  XCircle,
} from '@phosphor-icons/react';

const p = { size: '1em', 'aria-hidden': true, weight: 'bold' } as const;

/**
 * Astryx semantic icon names → Phosphor glyphs (`astryx docs icons`, "Theme Overrides").
 * Passed to defineTheme({icons}) so every Astryx component draws Phosphor icons.
 */
export const phosphorIconRegistry = {
  close: <X {...p} />,
  chevronDown: <CaretDown {...p} />,
  chevronLeft: <CaretLeft {...p} />,
  chevronRight: <CaretRight {...p} />,
  chevronsLeft: <CaretDoubleLeft {...p} />,
  chevronsRight: <CaretDoubleRight {...p} />,
  check: <Check {...p} />,
  success: <CheckCircle {...p} weight="fill" />,
  error: <XCircle {...p} weight="fill" />,
  warning: <Warning {...p} weight="fill" />,
  info: <Info {...p} weight="fill" />,
  calendar: <CalendarBlank {...p} />,
  clock: <Clock {...p} />,
  externalLink: <ArrowSquareOut {...p} />,
  menu: <List {...p} />,
  moreHorizontal: <DotsThree {...p} />,
  search: <MagnifyingGlass {...p} />,
  upload: <UploadSimple {...p} />,
  arrowUp: <ArrowUp {...p} />,
  arrowDown: <ArrowDown {...p} />,
  arrowsUpDown: <ArrowsDownUp {...p} />,
  funnel: <Funnel {...p} />,
  eyeSlash: <EyeSlash {...p} />,
  viewColumns: <Columns {...p} />,
  copy: <Copy {...p} />,
  checkDouble: <Checks {...p} />,
  wrench: <Wrench {...p} />,
  stop: <Stop {...p} />,
  microphone: <Microphone {...p} />,
} satisfies Record<string, ReactNode>;
