#!/usr/bin/env tsx
/**
 * pnpm seed:build — writes supabase/seed.sql from the demo studios in tenants/
 * (business.json with "demo": true). The seed uses the same admin_publish_tenant as
 * the pipeline, so seed and pipeline cannot drift. Media paths are content-addressed
 * and match what `pnpm tenant:publish` uploads (`pnpm demo:media` after a reset).
 *
 * Contents: demo studios (preview), local-only owner accounts, demo bookings and
 * payments relative to the time of `supabase db reset`.
 */
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { prepareMedia } from './images.ts';
import { listTenantSlugs, loadBusiness, ROOT } from './load.ts';
import { normalizeBusiness, type Business, type MediaPaths } from './schema.ts';

/** Deterministic UUID from a string (stable ids for demo rows). */
export function stableUuid(input: string): string {
  const h = createHash('sha256').update(input).digest('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
}

/** Local-only demo owner password (documented in SETUP.md; never used in production). */
export const demoOwnerPassword = (slug: string) => `demo-${slug}-local`;

interface DemoBooking {
  service: string;
  day: number;
  time: string;
  name: string;
  phone: string;
  car: string;
  status: 'confirmed' | 'arrived' | 'done' | 'cancelled' | 'no_show';
  paid?: number;
}

const PEOPLE = [
  ['Алексей Миронов', '+7 900 000-11-01', 'BMW 5 G30, графит'],
  ['Мария Соколова', '+7 900 000-11-02', 'Kia K5, белая'],
  ['Денис Ковалёв', '+7 900 000-11-03', 'Toyota Camry, чёрная'],
  ['Ольга Павлова', '+7 900 000-11-04', 'Volkswagen Tiguan'],
  ['Игорь Белов', '+7 900 000-11-05', 'Mercedes GLE'],
  ['Светлана Орлова', '+7 900 000-11-06', 'Hyundai Creta'],
  ['Руслан Фёдоров', '+7 900 000-11-07', 'Lada Vesta'],
  ['Анна Лебедева', '+7 900 000-11-08', 'Skoda Octavia'],
  ['Павел Никитин', '+7 900 000-11-09', 'Haval Jolion'],
  ['Елена Зайцева', '+7 900 000-11-10', 'Audi A6'],
] as const;

/** A believable week for the owner dashboard: history (done + paid), today, upcoming. */
function demoBookings(b: Business): DemoBooking[] {
  const svc = b.services.map((s) => s.key);
  const pick = (i: number) => svc[i % svc.length]!;
  const price = (key: string) => (b.services.find((s) => s.key === key)?.price ?? 0) * 100;
  const person = (i: number) => PEOPLE[i % PEOPLE.length]!;
  const rows: Array<[number, string, number, DemoBooking['status'], boolean]> = [
    [-6, '10:00', 0, 'done', true],
    [-5, '11:00', 1, 'done', true],
    [-4, '12:00', 5 % svc.length, 'done', true],
    [-3, '10:00', 2, 'done', true],
    [-2, '15:00', 0, 'no_show', false],
    [-1, '11:00', 1, 'done', true],
    [-1, '16:00', 0, 'cancelled', false],
    [0, '10:00', 0, 'done', true],
    [0, '12:00', 1, 'arrived', false],
    [0, '16:00', 0, 'confirmed', false],
    [1, '10:00', 2, 'confirmed', false],
    [1, '14:00', 0, 'confirmed', false],
    [2, '11:00', 5 % svc.length, 'confirmed', false],
    [3, '10:00', 3 % svc.length, 'confirmed', false],
    [5, '12:00', 1, 'confirmed', false],
    [8, '10:00', 4 % svc.length, 'confirmed', false],
  ];
  return rows.map(([day, time, svcIndex, status, paid], i) => {
    const service = pick(svcIndex);
    const [name, phone, car] = person(i);
    return { service, day, time, name, phone, car, status, paid: paid ? price(service) : 0 };
  });
}

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const dollar = (json: unknown) => `$cfg$${JSON.stringify(json)}$cfg$`;

export async function buildSeedSql(): Promise<string> {
  const parts: string[] = [
    '-- GENERATED by `pnpm seed:build` from tenants/*/business.json ("demo": true). Do not edit.',
    '-- Local development only: demo studios (preview), local owner accounts and demo',
    '-- bookings relative to the moment of `supabase db reset`. Never run in production.',
    '',
    `create or replace function pg_temp.seed_booking(
  p_slug text, p_service_key text, p_day int, p_time time, p_name text, p_phone text,
  p_car text, p_status text, p_paid_minor bigint)
returns void language plpgsql as $fn$
declare
  t public.tenants;
  s public.services;
  v_start timestamptz;
  r record;
  b public.bookings;
  i int := 0;
begin
  select * into t from public.tenants where slug = p_slug;
  select * into s from public.services where tenant_id = t.id and key = p_service_key;
  v_start := (((now() at time zone t.timezone)::date + p_day) + p_time) at time zone t.timezone;
  -- Keep demo bookings realistic: received and handed back within working hours.
  while i < 7 and not (private.is_open_at(t.id, v_start)
                       and private.is_open_at(t.id, v_start + make_interval(mins => s.duration_minutes))) loop
    v_start := v_start + case when p_day < 0 then interval '-1 day' else interval '1 day' end;
    i := i + 1;
  end loop;
  select * into r from private.place_booking(t.id, s.id, v_start, p_name, private.normalize_phone(p_phone),
    p_car, null, null, 'client', null, gen_random_uuid(), 'seed', true, now() - interval '7 days', null);
  if r.outcome <> 'created' then
    raise notice 'seed booking skipped (%): % % %', r.outcome, p_slug, p_service_key, v_start;
    return;
  end if;
  update public.bookings set created_at = least(v_start - interval '1 day', now()) where id = r.booking_id;
  select * into b from public.bookings where id = r.booking_id;
  if p_status in ('arrived', 'done') then
    update public.bookings set status = p_status, arrived_at = b.starts_at + interval '4 minutes',
      done_at = case when p_status = 'done' then least(b.ends_at, now()) end
    where id = b.id;
  elsif p_status = 'cancelled' then
    update public.bookings set status = 'cancelled', cancelled_at = b.starts_at - interval '20 hours',
      cancelled_by = 'client', cancel_reason = 'Планы изменились' where id = b.id;
    perform private.release_booking_occupancy(b.id);
  elsif p_status = 'no_show' then
    update public.bookings set status = 'no_show', no_show_at = b.starts_at + interval '30 minutes' where id = b.id;
    perform private.release_booking_occupancy(b.id);
  end if;
  if p_paid_minor > 0 then
    insert into public.payments (tenant_id, booking_id, kind, amount_minor, method, is_demo, idempotency_key, paid_at)
    values (t.id, b.id, 'payment', p_paid_minor, 'card', true, gen_random_uuid(),
            least(b.ends_at, now()));
  end if;
end;
$fn$;`,
    '',
  ];

  for (const slug of listTenantSlugs()) {
    const loaded = loadBusiness(slug);
    if (!loaded.business) throw new Error(`tenants/${slug}: ${loaded.errors.join('; ')}`);
    const b = loaded.business;
    if (!b.demo) continue;
    const tenantId = stableUuid(`tenant:${slug}`);
    const media = await prepareMedia(loaded.dir, b);
    const paths: MediaPaths = { logo_path: null, hero_path: null, works: {} };
    for (const m of media) {
      const path = `${tenantId}/config/${m.name}`;
      if (m.role === 'logo') paths.logo_path = path;
      else if (m.role === 'hero') paths.hero_path = path;
      else paths.works[m.role.slice(5)] = path;
    }
    const ownerId = stableUuid(`owner:${slug}`);
    const email = b.owner?.email ?? `owner@${slug}.example`;
    parts.push(
      `-- ${b.name} (${slug})`,
      `insert into public.tenants (id, slug, timezone, name, short_name, accent_color)
values (${lit(tenantId)}, ${lit(slug)}, ${lit(b.timezone)}, 'seed', 'seed', '#000000')
on conflict (slug) do nothing;`,
      `select public.admin_publish_tenant(${dollar(normalizeBusiness(b, paths))}::jsonb, '{}'::jsonb);`,
      `insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values (${lit(ownerId)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${lit(email)},
  extensions.crypt(${lit(demoOwnerPassword(slug))}, extensions.gen_salt('bf')), now(), '', '', '', '',
  '{"provider":"email","providers":["email"]}', '{}', now(), now())
on conflict (id) do nothing;`,
      `insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (${lit(stableUuid(`identity:${slug}`))}, ${lit(ownerId)}, ${lit(ownerId)},
  jsonb_build_object('sub', ${lit(ownerId)}, 'email', ${lit(email)}, 'email_verified', true), 'email', now(), now(), now())
on conflict do nothing;`,
      `select public.admin_add_member(${lit(slug)}, ${lit(ownerId)}, 'owner');`,
      ...demoBookings(b).map(
        (d) =>
          `select pg_temp.seed_booking(${lit(slug)}, ${lit(d.service)}, ${d.day}, ${lit(d.time)}, ${lit(d.name)}, ${lit(d.phone)}, ${lit(d.car)}, ${lit(d.status)}, ${d.paid ?? 0});`,
      ),
      '',
    );
  }
  return `${parts.join('\n')}\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const sql = await buildSeedSql();
  writeFileSync(join(ROOT, 'supabase', 'seed.sql'), sql);
  console.log(`✓ supabase/seed.sql (${sql.length} bytes)`);
}
